"""sqlite_baseline

Revision ID: 7477eaad542f
Revises: 
Create Date: 2026-10-01 09:46:45.126231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7477eaad542f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('code', sa.Enum('view_live_video', 'view_historical_video', 'view_incident_evidence', 'view_analytics', 'manage_users', 'manage_models', 'manage_cameras', 'export_data', 'delete_data', name='permission_code', native_enum=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('code', name=op.f('uq_permissions_code'))
    )
    op.create_table('products',
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('image_reference', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('sku', name=op.f('uq_products_sku'))
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_table('roles',
    sa.Column('code', sa.Enum('super_admin', 'org_admin', 'store_manager', 'security_manager', 'security_operator', 'analyst', 'auditor', 'view_only', name='role_code', native_enum=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('code', name=op.f('uq_roles_code'))
    )
    op.create_table('stores',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('timezone', sa.String(length=64), server_default='UTC', nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'maintenance', name='store_status', native_enum=False), server_default='active', nullable=False),
    sa.Column('bounds', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stores'))
    )
    op.create_index(op.f('ix_stores_status'), 'stores', ['status'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('audit_logs',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_audit_logs_store_id_stores'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_store_id'), 'audit_logs', ['store_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('incidents',
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'investigating', 'resolved', 'closed', name='incident_status', native_enum=False), server_default='open', nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='incident_severity', native_enum=False), server_default='medium', nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name=op.f('fk_incidents_assigned_to_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_incidents_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_incidents_store_id_stores'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incidents'))
    )
    op.create_index(op.f('ix_incidents_assigned_to'), 'incidents', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_incidents_created_by'), 'incidents', ['created_by'], unique=False)
    op.create_index(op.f('ix_incidents_severity'), 'incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_index(op.f('ix_incidents_store_id'), 'incidents', ['store_id'], unique=False)
    op.create_table('pos_scans',
    sa.Column('pos_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('product_sku', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('register_id', sa.String(length=64), nullable=False),
    sa.Column('transaction_id', sa.String(length=64), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('payment_status', sa.Enum('paid', 'pending', 'voided', 'refunded', name='pos_payment_status', native_enum=False), server_default='paid', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_pos_scans_quantity_positive')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_pos_scans_product_id_products'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_pos_scans_store_id_stores'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pos_scans'))
    )
    op.create_index(op.f('ix_pos_scans_pos_timestamp'), 'pos_scans', ['pos_timestamp'], unique=False)
    op.create_index(op.f('ix_pos_scans_product_id'), 'pos_scans', ['product_id'], unique=False)
    op.create_index(op.f('ix_pos_scans_product_sku'), 'pos_scans', ['product_sku'], unique=False)
    op.create_index(op.f('ix_pos_scans_register_id'), 'pos_scans', ['register_id'], unique=False)
    op.create_index(op.f('ix_pos_scans_store_id'), 'pos_scans', ['store_id'], unique=False)
    op.create_index(op.f('ix_pos_scans_transaction_id'), 'pos_scans', ['transaction_id'], unique=False)
    op.create_table('product_images',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('image_reference', sa.String(length=500), nullable=False),
    sa.Column('weight', sa.Float(), server_default=sa.text('(1.0)'), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_images_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_images'))
    )
    op.create_index(op.f('ix_product_images_product_id'), 'product_images', ['product_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_permissions')),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permissions_role_permission')
    )
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_user_roles_store_id_stores'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_roles')),
    sa.UniqueConstraint('user_id', 'role_id', 'store_id', name='uq_user_roles_user_role_store')
    )
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_store_id'), 'user_roles', ['store_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_table('zones',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('zone_type', sa.Enum('shelf', 'checkout', 'entrance', 'exit', 'restricted', 'customer_area', 'walkway', 'storage', 'staff_area', 'other', name='zone_type', native_enum=False), nullable=False),
    sa.Column('floor', sa.String(length=64), nullable=True),
    sa.Column('bounds', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_zones_store_id_stores'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_zones'))
    )
    op.create_index(op.f('ix_zones_store_id'), 'zones', ['store_id'], unique=False)
    op.create_index(op.f('ix_zones_zone_type'), 'zones', ['zone_type'], unique=False)
    op.create_table('cameras',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('floor', sa.String(length=64), nullable=True),
    sa.Column('source_type', sa.Enum('rtsp', 'file', 'simulation', name='camera_source_type', native_enum=False), server_default='rtsp', nullable=False),
    sa.Column('rtsp_url', sa.String(length=500), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('scale_factor', sa.Float(), nullable=True),
    sa.Column('resolution', sa.String(length=32), nullable=True),
    sa.Column('fps', sa.Integer(), nullable=True),
    sa.Column('processing_fps', sa.Integer(), nullable=True),
    sa.Column('detection_model', sa.String(length=100), nullable=True),
    sa.Column('orientation', sa.String(length=64), nullable=True),
    sa.Column('field_of_view', sa.Float(), nullable=True),
    sa.Column('map_x', sa.Float(), nullable=True),
    sa.Column('map_y', sa.Float(), nullable=True),
    sa.Column('facing_direction', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('active', 'disabled', 'faulted', 'removed', name='camera_status', native_enum=False), server_default='active', nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_successful_frame_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_heartbeat_latency_ms', sa.Float(), nullable=True),
    sa.Column('last_heartbeat_fps', sa.Float(), nullable=True),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gpu_assignment', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_cameras_store_id_stores'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_cameras_zone_id_zones'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cameras'))
    )
    op.create_index(op.f('ix_cameras_last_heartbeat_at'), 'cameras', ['last_heartbeat_at'], unique=False)
    op.create_index(op.f('ix_cameras_status'), 'cameras', ['status'], unique=False)
    op.create_index(op.f('ix_cameras_store_id'), 'cameras', ['store_id'], unique=False)
    op.create_index(op.f('ix_cameras_zone_id'), 'cameras', ['zone_id'], unique=False)
    op.create_table('persons',
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_zone_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('active', 'exited', 'unknown', name='person_status', native_enum=False), server_default='active', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['current_zone_id'], ['zones.id'], name=op.f('fk_persons_current_zone_id_zones'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_persons_store_id_stores'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_persons'))
    )
    op.create_index(op.f('ix_persons_current_zone_id'), 'persons', ['current_zone_id'], unique=False)
    op.create_index(op.f('ix_persons_last_seen_at'), 'persons', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_persons_status'), 'persons', ['status'], unique=False)
    op.create_index(op.f('ix_persons_store_id'), 'persons', ['store_id'], unique=False)
    op.create_table('shelves',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='active', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_shelves_store_id_stores'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_shelves_zone_id_zones'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shelves'))
    )
    op.create_index(op.f('ix_shelves_store_id'), 'shelves', ['store_id'], unique=False)
    op.create_index(op.f('ix_shelves_zone_id'), 'shelves', ['zone_id'], unique=False)
    op.create_table('zone_authorizations',
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('ref', sa.String(length=128), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_zone_authorizations_zone_id_zones'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_zone_authorizations'))
    )
    op.create_index(op.f('ix_zone_authorizations_zone_id'), 'zone_authorizations', ['zone_id'], unique=False)
    op.create_table('camera_heartbeats',
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('current_fps', sa.Float(), nullable=True),
    sa.Column('last_successful_frame_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('payload', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('fk_camera_heartbeats_camera_id_cameras'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_camera_heartbeats_store_id_stores'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_camera_heartbeats'))
    )
    op.create_index(op.f('ix_camera_heartbeats_camera_id'), 'camera_heartbeats', ['camera_id'], unique=False)
    op.create_index(op.f('ix_camera_heartbeats_reported_at'), 'camera_heartbeats', ['reported_at'], unique=False)
    op.create_index(op.f('ix_camera_heartbeats_store_id'), 'camera_heartbeats', ['store_id'], unique=False)
    op.create_table('camera_relationships',
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('related_camera_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.Enum('overlap', 'entry_exit', 'adjacent', 'blind_spot', name='camera_relationship_type', native_enum=False), nullable=False),
    sa.Column('directed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('geometry', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('fk_camera_relationships_camera_id_cameras'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_camera_id'], ['cameras.id'], name=op.f('fk_camera_relationships_related_camera_id_cameras'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_camera_relationships')),
    sa.UniqueConstraint('camera_id', 'related_camera_id', 'relationship_type', name='uq_camera_relationships_pair_type')
    )
    op.create_index(op.f('ix_camera_relationships_camera_id'), 'camera_relationships', ['camera_id'], unique=False)
    op.create_index(op.f('ix_camera_relationships_related_camera_id'), 'camera_relationships', ['related_camera_id'], unique=False)
    op.create_index(op.f('ix_camera_relationships_relationship_type'), 'camera_relationships', ['relationship_type'], unique=False)
    op.create_table('carts',
    sa.Column('cart_type', sa.Enum('cart', 'basket', 'other', name='cart_type', native_enum=False), server_default='cart', nullable=False),
    sa.Column('status', sa.Enum('active', 'abandoned', 'checked_out', 'unknown', name='cart_status', native_enum=False), server_default='active', nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('camera_id', sa.Integer(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('fk_carts_camera_id_cameras'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_carts_person_id_persons'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_carts_store_id_stores'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_carts_zone_id_zones'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_carts'))
    )
    op.create_index(op.f('ix_carts_camera_id'), 'carts', ['camera_id'], unique=False)
    op.create_index(op.f('ix_carts_last_seen_at'), 'carts', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_carts_person_id'), 'carts', ['person_id'], unique=False)
    op.create_index(op.f('ix_carts_status'), 'carts', ['status'], unique=False)
    op.create_index(op.f('ix_carts_store_id'), 'carts', ['store_id'], unique=False)
    op.create_index(op.f('ix_carts_zone_id'), 'carts', ['zone_id'], unique=False)
    op.create_table('events',
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('payload', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('metadata_schema_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('fk_events_camera_id_cameras'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_events_person_id_persons'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_events_product_id_products'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_events_store_id_stores'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_index(op.f('ix_events_camera_id'), 'events', ['camera_id'], unique=False)
    op.create_index(op.f('ix_events_event_timestamp'), 'events', ['event_timestamp'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_person_id'), 'events', ['person_id'], unique=False)
    op.create_index(op.f('ix_events_product_id'), 'events', ['product_id'], unique=False)
    op.create_index(op.f('ix_events_store_id'), 'events', ['store_id'], unique=False)
    op.create_table('journeys',
    sa.Column('journey_type', sa.Enum('person', 'product', name='journey_type', native_enum=False), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('active', 'completed', 'abandoned', name='journey_status', native_enum=False), server_default='active', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subject_key', sa.String(length=128), nullable=True),
    sa.Column('payload', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('(person_id IS NOT NULL AND product_id IS NULL) OR (product_id IS NOT NULL AND person_id IS NULL) OR (subject_key IS NOT NULL)', name=op.f('ck_journeys_subject_kind')),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_journeys_person_id_persons'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_journeys_product_id_products'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_journeys_store_id_stores'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journeys')),
    sa.UniqueConstraint('subject_key', name=op.f('uq_journeys_subject_key'))
    )
    op.create_index(op.f('ix_journeys_journey_type'), 'journeys', ['journey_type'], unique=False)
    op.create_index(op.f('ix_journeys_person_id'), 'journeys', ['person_id'], unique=False)
    op.create_index(op.f('ix_journeys_product_id'), 'journeys', ['product_id'], unique=False)
    op.create_index(op.f('ix_journeys_status'), 'journeys', ['status'], unique=False)
    op.create_index(op.f('ix_journeys_store_id'), 'journeys', ['store_id'], unique=False)
    op.create_table('shelf_products',
    sa.Column('shelf_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('expected_quantity', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_shelf_products_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shelf_id'], ['shelves.id'], name=op.f('fk_shelf_products_shelf_id_shelves'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_shelf_products_store_id_stores'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shelf_products')),
    sa.UniqueConstraint('shelf_id', 'product_id', name='uq_shelf_products_shelf_product')
    )
    op.create_index(op.f('ix_shelf_products_product_id'), 'shelf_products', ['product_id'], unique=False)
    op.create_index(op.f('ix_shelf_products_shelf_id'), 'shelf_products', ['shelf_id'], unique=False)
    op.create_index(op.f('ix_shelf_products_store_id'), 'shelf_products', ['store_id'], unique=False)
    op.create_table('tracks',
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bbox_summary', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('track_key', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('fk_tracks_camera_id_cameras'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_tracks_person_id_persons'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_tracks_store_id_stores'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tracks'))
    )
    op.create_index(op.f('ix_tracks_camera_id'), 'tracks', ['camera_id'], unique=False)
    op.create_index(op.f('ix_tracks_ended_at'), 'tracks', ['ended_at'], unique=False)
    op.create_index(op.f('ix_tracks_person_id'), 'tracks', ['person_id'], unique=False)
    op.create_index(op.f('ix_tracks_store_id'), 'tracks', ['store_id'], unique=False)
    op.create_index(op.f('ix_tracks_track_key'), 'tracks', ['track_key'], unique=False)
    op.create_table('camera_handoffs',
    sa.Column('source_track_id', sa.Integer(), nullable=True),
    sa.Column('target_track_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('matched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_camera_handoffs_person_id_persons'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_track_id'], ['tracks.id'], name=op.f('fk_camera_handoffs_source_track_id_tracks'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_camera_handoffs_store_id_stores'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_track_id'], ['tracks.id'], name=op.f('fk_camera_handoffs_target_track_id_tracks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_camera_handoffs'))
    )
    op.create_index(op.f('ix_camera_handoffs_person_id'), 'camera_handoffs', ['person_id'], unique=False)
    op.create_index(op.f('ix_camera_handoffs_source_track_id'), 'camera_handoffs', ['source_track_id'], unique=False)
    op.create_index(op.f('ix_camera_handoffs_store_id'), 'camera_handoffs', ['store_id'], unique=False)
    op.create_index(op.f('ix_camera_handoffs_target_track_id'), 'camera_handoffs', ['target_track_id'], unique=False)
    op.create_table('event_graph',
    sa.Column('source_event_id', sa.Integer(), nullable=False),
    sa.Column('target_event_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('source_event_id <> target_event_id', name=op.f('ck_event_graph_no_self_loop')),
    sa.ForeignKeyConstraint(['source_event_id'], ['events.id'], name=op.f('fk_event_graph_source_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_event_graph_store_id_stores'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_event_id'], ['events.id'], name=op.f('fk_event_graph_target_event_id_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_graph'))
    )
    op.create_index(op.f('ix_event_graph_relation_type'), 'event_graph', ['relation_type'], unique=False)
    op.create_index(op.f('ix_event_graph_source_event_id'), 'event_graph', ['source_event_id'], unique=False)
    op.create_index(op.f('ix_event_graph_store_id'), 'event_graph', ['store_id'], unique=False)
    op.create_index(op.f('ix_event_graph_target_event_id'), 'event_graph', ['target_event_id'], unique=False)
    op.create_table('journey_events',
    sa.Column('journey_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_journey_events_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], name=op.f('fk_journey_events_journey_id_journeys'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_journey_events_store_id_stores'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journey_events')),
    sa.UniqueConstraint('journey_id', 'event_id', name='uq_journey_events_journey_event'),
    sa.UniqueConstraint('journey_id', 'position', name='uq_journey_events_journey_position')
    )
    op.create_index(op.f('ix_journey_events_event_id'), 'journey_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_journey_events_journey_id'), 'journey_events', ['journey_id'], unique=False)
    op.create_index(op.f('ix_journey_events_store_id'), 'journey_events', ['store_id'], unique=False)
    op.create_table('product_detections',
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bounding_box', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('fk_product_detections_camera_id_cameras'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_product_detections_person_id_persons'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_detections_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_product_detections_store_id_stores'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], name=op.f('fk_product_detections_track_id_tracks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_detections'))
    )
    op.create_index(op.f('ix_product_detections_camera_id'), 'product_detections', ['camera_id'], unique=False)
    op.create_index(op.f('ix_product_detections_detected_at'), 'product_detections', ['detected_at'], unique=False)
    op.create_index(op.f('ix_product_detections_person_id'), 'product_detections', ['person_id'], unique=False)
    op.create_index(op.f('ix_product_detections_product_id'), 'product_detections', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_detections_store_id'), 'product_detections', ['store_id'], unique=False)
    op.create_index(op.f('ix_product_detections_track_id'), 'product_detections', ['track_id'], unique=False)
    op.create_table('risk_scores',
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('journey_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('score_value', sa.Integer(), nullable=False),
    sa.Column('signals', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('scoring_version', sa.String(length=64), nullable=True),
    sa.Column('model_id', sa.String(length=128), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('event_id IS NOT NULL OR journey_id IS NOT NULL', name=op.f('ck_risk_scores_lineage_anchor')),
    sa.CheckConstraint('score_value >= 0 AND score_value <= 100', name=op.f('ck_risk_scores_score_range')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_risk_scores_event_id_events'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], name=op.f('fk_risk_scores_journey_id_journeys'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_risk_scores_person_id_persons'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_risk_scores_store_id_stores'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_scores'))
    )
    op.create_index(op.f('ix_risk_scores_event_id'), 'risk_scores', ['event_id'], unique=False)
    op.create_index(op.f('ix_risk_scores_journey_id'), 'risk_scores', ['journey_id'], unique=False)
    op.create_index(op.f('ix_risk_scores_person_id'), 'risk_scores', ['person_id'], unique=False)
    op.create_index(op.f('ix_risk_scores_score_value'), 'risk_scores', ['score_value'], unique=False)
    op.create_index(op.f('ix_risk_scores_scored_at'), 'risk_scores', ['scored_at'], unique=False)
    op.create_index(op.f('ix_risk_scores_store_id'), 'risk_scores', ['store_id'], unique=False)
    op.create_table('track_frames',
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('frame_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bounding_box', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('frame_number', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_track_frames_store_id_stores'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], name=op.f('fk_track_frames_track_id_tracks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_track_frames'))
    )
    op.create_index(op.f('ix_track_frames_frame_timestamp'), 'track_frames', ['frame_timestamp'], unique=False)
    op.create_index(op.f('ix_track_frames_store_id'), 'track_frames', ['store_id'], unique=False)
    op.create_index(op.f('ix_track_frames_track_id'), 'track_frames', ['track_id'], unique=False)
    op.create_table('alerts',
    sa.Column('risk_score_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('open', 'reviewing', 'resolved', 'false_positive', 'escalated', name='alert_status', native_enum=False), server_default='open', nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'urgent', name='alert_priority', native_enum=False), server_default='medium', nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name=op.f('fk_alerts_assigned_to_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['risk_score_id'], ['risk_scores.id'], name=op.f('fk_alerts_risk_score_id_risk_scores'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_alerts_store_id_stores'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts')),
    sa.UniqueConstraint('risk_score_id', name=op.f('uq_alerts_risk_score_id'))
    )
    op.create_index(op.f('ix_alerts_assigned_to'), 'alerts', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_alerts_priority'), 'alerts', ['priority'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index(op.f('ix_alerts_store_id'), 'alerts', ['store_id'], unique=False)
    op.create_table('product_states',
    sa.Column('product_detection_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('camera_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.Enum('normal', 'picked', 'carried', 'concealed', 'in_cart', 'returned', 'transferred', 'dropped', 'purchased', 'pending_checkout_resolution', 'unknown', 'review_required', name='product_state', native_enum=False), nullable=False),
    sa.Column('entered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('fk_product_states_camera_id_cameras'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_product_states_person_id_persons'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_detection_id'], ['product_detections.id'], name=op.f('fk_product_states_product_detection_id_product_detections'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_states_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_product_states_store_id_stores'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_states'))
    )
    op.create_index(op.f('ix_product_states_camera_id'), 'product_states', ['camera_id'], unique=False)
    op.create_index(op.f('ix_product_states_exited_at'), 'product_states', ['exited_at'], unique=False)
    op.create_index(op.f('ix_product_states_person_id'), 'product_states', ['person_id'], unique=False)
    op.create_index(op.f('ix_product_states_product_detection_id'), 'product_states', ['product_detection_id'], unique=False)
    op.create_index(op.f('ix_product_states_product_id'), 'product_states', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_states_state'), 'product_states', ['state'], unique=False)
    op.create_index(op.f('ix_product_states_store_id'), 'product_states', ['store_id'], unique=False)
    op.create_table('evidence',
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('evidence_type', sa.Enum('frame', 'clip', 'snapshot', 'track', 'detection', 'other', name='evidence_type', native_enum=False), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('detection_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('camera_id', sa.Integer(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], name=op.f('fk_evidence_alert_id_alerts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('fk_evidence_camera_id_cameras'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['detection_id'], ['product_detections.id'], name=op.f('fk_evidence_detection_id_product_detections'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_evidence_incident_id_incidents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_evidence_person_id_persons'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_evidence_store_id_stores'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], name=op.f('fk_evidence_track_id_tracks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence'))
    )
    op.create_index(op.f('ix_evidence_alert_id'), 'evidence', ['alert_id'], unique=False)
    op.create_index(op.f('ix_evidence_camera_id'), 'evidence', ['camera_id'], unique=False)
    op.create_index(op.f('ix_evidence_detection_id'), 'evidence', ['detection_id'], unique=False)
    op.create_index(op.f('ix_evidence_evidence_type'), 'evidence', ['evidence_type'], unique=False)
    op.create_index(op.f('ix_evidence_incident_id'), 'evidence', ['incident_id'], unique=False)
    op.create_index(op.f('ix_evidence_person_id'), 'evidence', ['person_id'], unique=False)
    op.create_index(op.f('ix_evidence_store_id'), 'evidence', ['store_id'], unique=False)
    op.create_index(op.f('ix_evidence_track_id'), 'evidence', ['track_id'], unique=False)
    op.create_table('incident_alerts',
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], name=op.f('fk_incident_alerts_alert_id_alerts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_incident_alerts_incident_id_incidents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_incident_alerts_store_id_stores'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incident_alerts')),
    sa.UniqueConstraint('incident_id', 'alert_id', name='uq_incident_alerts_incident_alert')
    )
    op.create_index(op.f('ix_incident_alerts_alert_id'), 'incident_alerts', ['alert_id'], unique=False)
    op.create_index(op.f('ix_incident_alerts_incident_id'), 'incident_alerts', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incident_alerts_store_id'), 'incident_alerts', ['store_id'], unique=False)
    op.create_table('review_feedback',
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('decision', sa.Enum('true_event', 'false_positive', 'normal_behavior', 'misplaced_product', 'returned_product', 'unknown', 'staff_activity', 'camera_error', name='feedback_decision', native_enum=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], name=op.f('fk_review_feedback_alert_id_alerts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_review_feedback_incident_id_incidents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_review_feedback_store_id_stores'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_review_feedback_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_feedback'))
    )
    op.create_index(op.f('ix_review_feedback_alert_id'), 'review_feedback', ['alert_id'], unique=False)
    op.create_index(op.f('ix_review_feedback_decision'), 'review_feedback', ['decision'], unique=False)
    op.create_index(op.f('ix_review_feedback_incident_id'), 'review_feedback', ['incident_id'], unique=False)
    op.create_index(op.f('ix_review_feedback_store_id'), 'review_feedback', ['store_id'], unique=False)
    op.create_index(op.f('ix_review_feedback_user_id'), 'review_feedback', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_feedback_user_id'), table_name='review_feedback')
    op.drop_index(op.f('ix_review_feedback_store_id'), table_name='review_feedback')
    op.drop_index(op.f('ix_review_feedback_incident_id'), table_name='review_feedback')
    op.drop_index(op.f('ix_review_feedback_decision'), table_name='review_feedback')
    op.drop_index(op.f('ix_review_feedback_alert_id'), table_name='review_feedback')
    op.drop_table('review_feedback')
    op.drop_index(op.f('ix_incident_alerts_store_id'), table_name='incident_alerts')
    op.drop_index(op.f('ix_incident_alerts_incident_id'), table_name='incident_alerts')
    op.drop_index(op.f('ix_incident_alerts_alert_id'), table_name='incident_alerts')
    op.drop_table('incident_alerts')
    op.drop_index(op.f('ix_evidence_track_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_store_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_person_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_incident_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_evidence_type'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_detection_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_camera_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_alert_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_product_states_store_id'), table_name='product_states')
    op.drop_index(op.f('ix_product_states_state'), table_name='product_states')
    op.drop_index(op.f('ix_product_states_product_id'), table_name='product_states')
    op.drop_index(op.f('ix_product_states_product_detection_id'), table_name='product_states')
    op.drop_index(op.f('ix_product_states_person_id'), table_name='product_states')
    op.drop_index(op.f('ix_product_states_exited_at'), table_name='product_states')
    op.drop_index(op.f('ix_product_states_camera_id'), table_name='product_states')
    op.drop_table('product_states')
    op.drop_index(op.f('ix_alerts_store_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_priority'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_assigned_to'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_track_frames_track_id'), table_name='track_frames')
    op.drop_index(op.f('ix_track_frames_store_id'), table_name='track_frames')
    op.drop_index(op.f('ix_track_frames_frame_timestamp'), table_name='track_frames')
    op.drop_table('track_frames')
    op.drop_index(op.f('ix_risk_scores_store_id'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_scored_at'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_score_value'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_person_id'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_journey_id'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_event_id'), table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_index(op.f('ix_product_detections_track_id'), table_name='product_detections')
    op.drop_index(op.f('ix_product_detections_store_id'), table_name='product_detections')
    op.drop_index(op.f('ix_product_detections_product_id'), table_name='product_detections')
    op.drop_index(op.f('ix_product_detections_person_id'), table_name='product_detections')
    op.drop_index(op.f('ix_product_detections_detected_at'), table_name='product_detections')
    op.drop_index(op.f('ix_product_detections_camera_id'), table_name='product_detections')
    op.drop_table('product_detections')
    op.drop_index(op.f('ix_journey_events_store_id'), table_name='journey_events')
    op.drop_index(op.f('ix_journey_events_journey_id'), table_name='journey_events')
    op.drop_index(op.f('ix_journey_events_event_id'), table_name='journey_events')
    op.drop_table('journey_events')
    op.drop_index(op.f('ix_event_graph_target_event_id'), table_name='event_graph')
    op.drop_index(op.f('ix_event_graph_store_id'), table_name='event_graph')
    op.drop_index(op.f('ix_event_graph_source_event_id'), table_name='event_graph')
    op.drop_index(op.f('ix_event_graph_relation_type'), table_name='event_graph')
    op.drop_table('event_graph')
    op.drop_index(op.f('ix_camera_handoffs_target_track_id'), table_name='camera_handoffs')
    op.drop_index(op.f('ix_camera_handoffs_store_id'), table_name='camera_handoffs')
    op.drop_index(op.f('ix_camera_handoffs_source_track_id'), table_name='camera_handoffs')
    op.drop_index(op.f('ix_camera_handoffs_person_id'), table_name='camera_handoffs')
    op.drop_table('camera_handoffs')
    op.drop_index(op.f('ix_tracks_track_key'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_store_id'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_person_id'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_ended_at'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_camera_id'), table_name='tracks')
    op.drop_table('tracks')
    op.drop_index(op.f('ix_shelf_products_store_id'), table_name='shelf_products')
    op.drop_index(op.f('ix_shelf_products_shelf_id'), table_name='shelf_products')
    op.drop_index(op.f('ix_shelf_products_product_id'), table_name='shelf_products')
    op.drop_table('shelf_products')
    op.drop_index(op.f('ix_journeys_store_id'), table_name='journeys')
    op.drop_index(op.f('ix_journeys_status'), table_name='journeys')
    op.drop_index(op.f('ix_journeys_product_id'), table_name='journeys')
    op.drop_index(op.f('ix_journeys_person_id'), table_name='journeys')
    op.drop_index(op.f('ix_journeys_journey_type'), table_name='journeys')
    op.drop_table('journeys')
    op.drop_index(op.f('ix_events_store_id'), table_name='events')
    op.drop_index(op.f('ix_events_product_id'), table_name='events')
    op.drop_index(op.f('ix_events_person_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_event_timestamp'), table_name='events')
    op.drop_index(op.f('ix_events_camera_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_carts_zone_id'), table_name='carts')
    op.drop_index(op.f('ix_carts_store_id'), table_name='carts')
    op.drop_index(op.f('ix_carts_status'), table_name='carts')
    op.drop_index(op.f('ix_carts_person_id'), table_name='carts')
    op.drop_index(op.f('ix_carts_last_seen_at'), table_name='carts')
    op.drop_index(op.f('ix_carts_camera_id'), table_name='carts')
    op.drop_table('carts')
    op.drop_index(op.f('ix_camera_relationships_relationship_type'), table_name='camera_relationships')
    op.drop_index(op.f('ix_camera_relationships_related_camera_id'), table_name='camera_relationships')
    op.drop_index(op.f('ix_camera_relationships_camera_id'), table_name='camera_relationships')
    op.drop_table('camera_relationships')
    op.drop_index(op.f('ix_camera_heartbeats_store_id'), table_name='camera_heartbeats')
    op.drop_index(op.f('ix_camera_heartbeats_reported_at'), table_name='camera_heartbeats')
    op.drop_index(op.f('ix_camera_heartbeats_camera_id'), table_name='camera_heartbeats')
    op.drop_table('camera_heartbeats')
    op.drop_index(op.f('ix_zone_authorizations_zone_id'), table_name='zone_authorizations')
    op.drop_table('zone_authorizations')
    op.drop_index(op.f('ix_shelves_zone_id'), table_name='shelves')
    op.drop_index(op.f('ix_shelves_store_id'), table_name='shelves')
    op.drop_table('shelves')
    op.drop_index(op.f('ix_persons_store_id'), table_name='persons')
    op.drop_index(op.f('ix_persons_status'), table_name='persons')
    op.drop_index(op.f('ix_persons_last_seen_at'), table_name='persons')
    op.drop_index(op.f('ix_persons_current_zone_id'), table_name='persons')
    op.drop_table('persons')
    op.drop_index(op.f('ix_cameras_zone_id'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_store_id'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_status'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_last_heartbeat_at'), table_name='cameras')
    op.drop_table('cameras')
    op.drop_index(op.f('ix_zones_zone_type'), table_name='zones')
    op.drop_index(op.f('ix_zones_store_id'), table_name='zones')
    op.drop_table('zones')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_store_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_product_images_product_id'), table_name='product_images')
    op.drop_table('product_images')
    op.drop_index(op.f('ix_pos_scans_transaction_id'), table_name='pos_scans')
    op.drop_index(op.f('ix_pos_scans_store_id'), table_name='pos_scans')
    op.drop_index(op.f('ix_pos_scans_register_id'), table_name='pos_scans')
    op.drop_index(op.f('ix_pos_scans_product_sku'), table_name='pos_scans')
    op.drop_index(op.f('ix_pos_scans_product_id'), table_name='pos_scans')
    op.drop_index(op.f('ix_pos_scans_pos_timestamp'), table_name='pos_scans')
    op.drop_table('pos_scans')
    op.drop_index(op.f('ix_incidents_store_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_severity'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_created_by'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_assigned_to'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_store_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_index(op.f('ix_stores_status'), table_name='stores')
    op.drop_table('stores')
    op.drop_table('roles')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    op.drop_table('permissions')
    # ### end Alembic commands ###
