import os
from pathlib import Path

def patch_autogenerated_migration():
    migrations_dir = Path("c:/Projects/AI_CC/database/migrations/versions")
    for file in migrations_dir.glob("*_sqlite_baseline.py"):
        content = file.read_text(encoding="utf-8")
        
        # Replace sa.Column("id", sa.BigInteger(), ... with sa.Integer() for SQLite autoincrement
        content = content.replace("sa.BigInteger()", "sa.Integer()")
        
        file.write_text(content, encoding="utf-8")

if __name__ == "__main__":
    patch_autogenerated_migration()
    print("Patched BigInteger to Integer in sqlite migration.")
