apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: smartretail

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - kafka-broker.yaml
  - backend-deployment.yaml
  - backend-hpa.yaml
  - worker-deployment.yaml
  - frontend-deployment.yaml
  - ingress.yaml
